services:
  limitr:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7654:7654" # Make sure this is the same port as the one in your application, and make sure to add the port to the environment variable below
    networks:
      - containerNetwork
    volumes:
      - ./ssl:/ssl # Replace the left side with the path to your SSL certificates
    environment: # Define the environment variables, available in the docs
      - FORWARD_URL=https://www.beehive.net
      - RATE_LIMIT=50
      - TIME_WINDOW=120
      - REDIS_ADDR=redis:6379 # Don't change this unless you know what you're doing
    depends_on:
      - redis
  redis: # Don't change anything in this section unless you know what you're doing
    image: redis:latest
    networks:
      - containerNetwork
    volumes:
      - ./redis-data:/data
networks:
  containerNetwork:
    driver: bridge