services:
  limitr:
    build: # Don't change anything in this section unless you know what you're doing
      context: .
      dockerfile: Dockerfile
    ports:
      - "7654:7654" # Change this on ONLY the left side if you want to host on a different port
    networks: # Don't change anything in this section unless you know what you're doing
      - containerNetwork
    volumes:
      - ./ssl:/ssl # Replace ONLY the left side with the path to your SSL certificates
    environment: # HERE you can define the environment variables, details available in the README
      - FORWARD_URL=https://www.beehive.net # The URL to forward the requests to
      - RATE_LIMIT=50 # Requests allowed per time window
      - TIME_WINDOW=120 # Time window in seconds
      - REDIS_ADDR=redis:6379 # Don't change this unless you know what you're doing
      # - USE_TLS=true # Uncomment this line if you want to use TLS and have SSL certificates (both .key and .pem files). Make sure to set the correct path to the containing folder in the 'volumes' section above
      # For setting the host PORT, instead of using the environment variable please change the left side above under 'ports'
    depends_on: # Don't change anything in this section unless you know what you're doing
      - redis
  redis: # Don't change anything in this section unless you know what you're doing
    image: redis:latest
    networks:
      - containerNetwork
    volumes:
      - ./redis-data:/data
networks: # Don't change anything in this section unless you know what you're doing
  containerNetwork:
    driver: bridge