services:
  limitr:
    build: # Don't change anything in this section unless you know what you're doing
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:7654:7654" # Don't change this unless you know what you're doing
    networks: # Don't change anything in this section unless you know what you're doing
      - redisNetwork
    volumes:
      - ./ssl:/ssl # Replace ONLY the left side with the path to your SSL certificates
    restart: unless-stopped
    environment: # HERE you can define the environment variables, details available in the README
      - FORWARD_URL=http://10.100.6.250:8080 # The URL to forward the requests to
      - RATE_LIMIT=5 # Requests allowed per time window
      - TIME_WINDOW=7 # Time window in seconds
      - REDIS_ADDR=redis:6379 # Don't change this unless you know what you're doing
      - IP_IN_HEADER=true # Don't change this unless you know what you're doing
      - VERBOSE_MODE=true # Uncomment this line if you want to see the logs in the console
      # - USE_TLS=true # Uncomment this line if you want to use TLS and have SSL certificates (both .key and .pem files). Make sure to set the correct path to the containing folder in the 'volumes' section above
    depends_on: # Don't change anything in this section unless you know what you're doing
      - redis
      - nginx
  redis: # Don't change anything in this section unless you know what you're doing
    image: redis:latest
    networks:
      - redisNetwork
    restart: unless-stopped
    volumes:
      - ./redis-data:/data
  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./nginxconfig/nginx.conf:/etc/nginx/nginx.conf # For setting the host PORT, instead of using the environment variable please change the nginxconfig/nginx.conf file
    restart: unless-stopped
networks: # Don't change anything in this section unless you know what you're doing
  redisNetwork:
    driver: bridge
